package io.github.snoob.consolesounds;

import com.terraformersmc.modmenu.api.ModMenuApi;
import com.terraformersmc.modmenu.api.ConfigScreenFactory;
import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.IntegerSliderControllerBuilder;
import dev.isxander.yacl3.api.controller.TickBoxControllerBuilder;
import net.minecraft.network.chat.Component;

public class ConsoleSoundsModMenu implements ModMenuApi {

    @Override
    public ConfigScreenFactory<?> getModConfigScreenFactory() {
        return parent -> YetAnotherConfigLib.createBuilder()
                .title(Component.translatable("consolesounds.config.title"))
                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("consolesounds.config.category.enable.title"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Component.translatable("consolesounds.config.option.enableHoverSounds"))
                                        .binding(true, () -> ConsoleSoundsConfig.enableHoverSounds, newVal -> ConsoleSoundsConfig.enableHoverSounds = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("consolesounds.config.option.enableInGameClickSounds"))
                                .binding(true, () -> ConsoleSoundsConfig.enableInGameClickSounds, newVal -> ConsoleSoundsConfig.enableInGameClickSounds = newVal)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("consolesounds.config.option.enableCraftingSounds"))
                                .binding(true, () -> ConsoleSoundsConfig.enableCraftingSounds, newVal -> ConsoleSoundsConfig.enableCraftingSounds = newVal)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("consolesounds.config.option.enableSliderSounds"))
                                .binding(true, () -> ConsoleSoundsConfig.enableSliderSounds, newVal -> ConsoleSoundsConfig.enableSliderSounds = newVal)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("consolesounds.config.option.playSoundOnPauseMenu"))
                                .binding(true, () -> ConsoleSoundsConfig.playSoundOnPauseMenu, newVal -> ConsoleSoundsConfig.playSoundOnPauseMenu = newVal)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("consolesounds.config.option.playSoundOnInGameMenu"))
                                .binding(true, () -> ConsoleSoundsConfig.playSoundOnInGameMenu, newVal -> ConsoleSoundsConfig.playSoundOnInGameMenu = newVal)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("consolesounds.config.option.playSoundOnMenuExit"))
                                .binding(true, () -> ConsoleSoundsConfig.playSoundOnMenuExit, newVal -> ConsoleSoundsConfig.playSoundOnMenuExit = newVal)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("consolesounds.config.option.playSoundOnInGameMenuExit"))
                                .binding(true, () -> ConsoleSoundsConfig.playSoundOnInGameMenuExit, newVal -> ConsoleSoundsConfig.playSoundOnInGameMenuExit = newVal)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .build()).save(ConsoleSoundsConfig.HANDLER::save)
                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("consolesounds.config.category.volume.title"))
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("consolesounds.config.option.onInGameMenuExitVolume"))
                                .binding(100, () -> ConsoleSoundsConfig.onInGameMenuExitVolume, newVal -> ConsoleSoundsConfig.onInGameMenuExitVolume = newVal)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0,100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("consolesounds.config.option.menuExitVolume"))
                                .binding(100, () -> ConsoleSoundsConfig.menuExitVolume, newVal -> ConsoleSoundsConfig.menuExitVolume = newVal)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0,100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("consolesounds.config.option.inGameMenuVolume"))
                                .binding(100, () -> ConsoleSoundsConfig.inGameMenuVolume, newVal -> ConsoleSoundsConfig.inGameMenuVolume = newVal)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0,100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("consolesounds.config.option.onPauseMenuVolume"))
                                .binding(100, () -> ConsoleSoundsConfig.onPauseMenuVolume, newVal -> ConsoleSoundsConfig.onPauseMenuVolume = newVal)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0,100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("consolesounds.config.option.sliderVolume"))
                                .binding(100, () -> ConsoleSoundsConfig.sliderVolume, newVal -> ConsoleSoundsConfig.sliderVolume = newVal)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0,100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("consolesounds.config.option.craftingVolume"))
                                .binding(100, () -> ConsoleSoundsConfig.craftingVolume, newVal -> ConsoleSoundsConfig.craftingVolume = newVal)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0,100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("consolesounds.config.option.inGameClickVolume"))
                                .binding(100, () -> ConsoleSoundsConfig.inGameClickVolume, newVal -> ConsoleSoundsConfig.inGameClickVolume = newVal)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0,100).step(1))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("consolesounds.config.option.hoverVolume"))
                                .binding(100, () -> ConsoleSoundsConfig.hoverVolume, newVal -> ConsoleSoundsConfig.hoverVolume = newVal)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0,100).step(1))
                                .build())
                        .build()).save(ConsoleSoundsConfig.HANDLER::save)
                .build().generateScreen(parent);
    }
}
